In [1]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, mean_squared_error, confusion_matrix, cohen_kappa_score
from sklearn.model_selection import RandomizedSearchCV

from evaluation import quadratic_weighted_kappa
from cleaning import clean_data

In [2]:
X_train, Y_train, X_test, Y_test = clean_data('./petfinder-adoption-prediction/train/train.csv')

'''rf = RandomForestClassifier()

hyper_params = {
    'criterion':['entropy'],
    'max_depth': range(40,100),
    'max_features': range(50,150),
    'max_leaf_nodes': range(2,50),
    'min_samples_leaf': range(20,40),
    'n_estimators': range(300,600,10)
}

model_cv = RandomizedSearchCV(estimator=rf,param_distributions=hyper_params,verbose=1)
model_cv.fit(X_train,Y_train)
print(model_cv.best_score_)
print(model_cv.best_estimator_)'''

"rf = RandomForestClassifier()\n\nhyper_params = {\n    'criterion':['entropy'],\n    'max_depth': range(40,100),\n    'max_features': range(50,150),\n    'max_leaf_nodes': range(2,50),\n    'min_samples_leaf': range(20,40),\n    'n_estimators': range(300,600,10)\n}\n\nmodel_cv = RandomizedSearchCV(estimator=rf,param_distributions=hyper_params,verbose=1)\nmodel_cv.fit(X_train,Y_train)\nprint(model_cv.best_score_)\nprint(model_cv.best_estimator_)"

In [3]:
rf = RandomForestClassifier(criterion='entropy', max_depth=61, max_features=90,
                       max_leaf_nodes=45, min_samples_leaf=27,
                       n_estimators=410)
rf.fit(X_train, Y_train)
predictions = rf.predict(X_test)
print('Confusion Matrix\n',confusion_matrix(Y_test, predictions))
print('Cohen Kappa', cohen_kappa_score(Y_test, predictions, weights='quadratic'))
print('Accuracy Score', accuracy_score(Y_test, predictions))
print('MSE', mean_squared_error(Y_test, predictions))

Confusion Matrix
 [[  0  39  32   9  47]
 [  0 231 369  51 256]
 [  0 153 496 137 461]
 [  0  98 301 145 415]
 [  0  83 243  46 886]]
Cohen Kappa 0.296644337072831
Accuracy Score 0.39084037349933304
MSE 1.9751000444642064
