In [1]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, mean_squared_error, confusion_matrix, cohen_kappa_score
from sklearn.model_selection import RandomizedSearchCV
from sklearn.utils.class_weight import compute_sample_weight

from cleaning import clean_data

In [2]:
X_train, Y_train, X_test, Y_test = clean_data('./petfinder-adoption-prediction/train/train.csv')
sample_weights = compute_sample_weight('balanced', Y_train)

'''rf = RandomForestClassifier()

hyper_params = {
    'criterion':['entropy'],
    'max_depth': range(40,100),
    'max_features': range(50,150),
    'max_leaf_nodes': range(2,50),
    'min_samples_leaf': range(20,40),
    'n_estimators': range(300,600,10)
}

model_cv = RandomizedSearchCV(estimator=rf,param_distributions=hyper_params,verbose=1)
model_cv.fit(X_train,Y_train)
print(model_cv.best_score_)
print(model_cv.best_estimator_)'''

"rf = RandomForestClassifier()\n\nhyper_params = {\n    'criterion':['entropy'],\n    'max_depth': range(40,100),\n    'max_features': range(50,150),\n    'max_leaf_nodes': range(2,50),\n    'min_samples_leaf': range(20,40),\n    'n_estimators': range(300,600,10)\n}\n\nmodel_cv = RandomizedSearchCV(estimator=rf,param_distributions=hyper_params,verbose=1)\nmodel_cv.fit(X_train,Y_train)\nprint(model_cv.best_score_)\nprint(model_cv.best_estimator_)"

In [12]:
rf = RandomForestClassifier(criterion='entropy', max_depth=61, max_features=90,
                    max_leaf_nodes=45, min_samples_leaf=27,
                    n_estimators=410)
rf.fit(X_train, Y_train)
#rf.fit(X_train, Y_train,sample_weight=sample_weights)
predictions = rf.predict(X_test)
print('Confusion Matrix\n',confusion_matrix(Y_test, predictions))
print('Cohen Kappa', cohen_kappa_score(Y_test, predictions, weights='quadratic'))
print('Test Accuracy Score', accuracy_score(Y_test, predictions))
print('Train Accuracy Score', accuracy_score(Y_train, rf.predict(X_train)))

Confusion Matrix
 [[  0  37  35   7  48]
 [  0 232 366  50 259]
 [  0 145 506 135 461]
 [  0  98 305 140 416]
 [  0  85 241  43 889]]
Cohen Kappa 0.29436479094808454
Test Accuracy Score 0.3928412627834593
Train Accuracy Score 0.43020485945688425
