In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics import accuracy_score, mean_squared_error, confusion_matrix, cohen_kappa_score
from sklearn.model_selection import RandomizedSearchCV
import matplotlib.pyplot as plt

import xgboost as xgb

from cleaning import clean_data

In [2]:
X_train, Y_train, X_test, Y_test = clean_data('./petfinder-adoption-prediction/train/train.csv')
train = xgb.DMatrix(X_train, label = Y_train)
test = xgb.DMatrix(X_test, label = Y_test)

In [3]:
'''params = {
    'max_depth' : 6,
    'eta' : 0.3,
    'objective' : 'multi:softmax',
    'num_class':5
}
epochs = 25
model = xgb.train(params, train, epochs)
Y_pred = model.predict(test)'''

"params = {\n    'max_depth' : 6,\n    'eta' : 0.3,\n    'objective' : 'multi:softmax',\n    'num_class':5\n}\nepochs = 25\nmodel = xgb.train(params, train, epochs)\nY_pred = model.predict(test)"

In [4]:
'''hyper_params = {
    'learning_rate': np.arange(0.01, 0.5, 0.05),
    'max_depth':range(3,10),
    'colsample_bytree' : np.arange(0.5, 1, 0.05),
    'objective': ['multi:softmax'],
    'num_class':[5],
}

model = xgb.XGBClassifier()
search = RandomizedSearchCV(model, param_distributions=hyper_params, n_iter=30, cv=3)
search.fit(X_train, Y_train)'''

"hyper_params = {\n    'learning_rate': np.arange(0.01, 0.5, 0.05),\n    'max_depth':range(3,10),\n    'colsample_bytree' : np.arange(0.5, 1, 0.05),\n    'objective': ['multi:softmax'],\n    'num_class':[5],\n}\n\nmodel = xgb.XGBClassifier()\nsearch = RandomizedSearchCV(model, param_distributions=hyper_params, n_iter=30, cv=3)\nsearch.fit(X_train, Y_train)"

In [5]:
'''model = xgb.XGBClassifier(
    learning_rate = 0.1,
    n_estimators = 1000,
    max_depth = 5,
    min_child_weight = 1,
    gamma = 0,
    subsample = 0.8,
    colsample_bytree = 0.8,
    objective = 'multi:softmax',
    num_class = 5,
)
xgb_param = model.get_xgb_params()
cvresult = xgb.cv(xgb_param, train, num_boost_round=model.get_params()['n_estimators'], nfold=5,
            metrics='auc', early_stopping_rounds=50)
model.set_params(n_estimators=cvresult.shape[0])
model.fit(X_train, Y_train)
Y_pred = model.predict(X_test)'''

"model = xgb.XGBClassifier(\n    learning_rate = 0.1,\n    n_estimators = 1000,\n    max_depth = 5,\n    min_child_weight = 1,\n    gamma = 0,\n    subsample = 0.8,\n    colsample_bytree = 0.8,\n    objective = 'multi:softmax',\n    num_class = 5,\n)\nxgb_param = model.get_xgb_params()\ncvresult = xgb.cv(xgb_param, train, num_boost_round=model.get_params()['n_estimators'], nfold=5,\n            metrics='auc', early_stopping_rounds=50)\nmodel.set_params(n_estimators=cvresult.shape[0])\nmodel.fit(X_train, Y_train)\nY_pred = model.predict(X_test)"

In [6]:
'''hyper_params = {'max_depth':range(1,10),
                'min_child_weight':range(1,6)}
search = RandomizedSearchCV(estimator=xgb.XGBClassifier(learning_rate = 0.1, n_estimators=141,
                                                        gamma=0, subsample=0.8, colsample_bytree=0.8,objective= 'multi:softmax'), 
                            param_distributions = hyper_params, verbose = 1, cv = 5)
search.fit(X_train, Y_train)
print(search.best_score_)
print(search.best_estimator_)'''

"hyper_params = {'max_depth':range(1,10),\n                'min_child_weight':range(1,6)}\nsearch = RandomizedSearchCV(estimator=xgb.XGBClassifier(learning_rate = 0.1, n_estimators=141,\n                                                        gamma=0, subsample=0.8, colsample_bytree=0.8,objective= 'multi:softmax'), \n                            param_distributions = hyper_params, verbose = 1, cv = 5)\nsearch.fit(X_train, Y_train)\nprint(search.best_score_)\nprint(search.best_estimator_)"

In [7]:
'''hyper_params = {'gamma':[i/10.0 for i in range(0,5)]}
search = RandomizedSearchCV(estimator=xgb.XGBClassifier(learning_rate = 0.1, n_estimators=141, max_depth=5, min_child_weight=3, 
                                                        subsample=0.8, colsample_bytree=0.8,objective= 'multi:softmax'), 
                            param_distributions = hyper_params, verbose = 1, cv = 5)
search.fit(X_train, Y_train)
print(search.best_score_)
print(search.best_estimator_)'''

"hyper_params = {'gamma':[i/10.0 for i in range(0,5)]}\nsearch = RandomizedSearchCV(estimator=xgb.XGBClassifier(learning_rate = 0.1, n_estimators=141, max_depth=5, min_child_weight=3, \n                                                        subsample=0.8, colsample_bytree=0.8,objective= 'multi:softmax'), \n                            param_distributions = hyper_params, verbose = 1, cv = 5)\nsearch.fit(X_train, Y_train)\nprint(search.best_score_)\nprint(search.best_estimator_)"

In [8]:
'''hyper_params = {'subsample':[i/10.0 for i in range(6,10)],
                'colsample_bytree':[i/10.0 for i in range(6,10)]
                }
search = RandomizedSearchCV(estimator=xgb.XGBClassifier(learning_rate = 0.1, n_estimators=141, max_depth=5, min_child_weight=3, 
                                                        gamma =0.4,objective= 'multi:softmax'), 
                            param_distributions = hyper_params, verbose = 1, cv = 5)
search.fit(X_train, Y_train)
print(search.best_score_)
print(search.best_estimator_)
'''

"hyper_params = {'subsample':[i/10.0 for i in range(6,10)],\n                'colsample_bytree':[i/10.0 for i in range(6,10)]\n                }\nsearch = RandomizedSearchCV(estimator=xgb.XGBClassifier(learning_rate = 0.1, n_estimators=141, max_depth=5, min_child_weight=3, \n                                                        gamma =0.4,objective= 'multi:softmax'), \n                            param_distributions = hyper_params, verbose = 1, cv = 5)\nsearch.fit(X_train, Y_train)\nprint(search.best_score_)\nprint(search.best_estimator_)\n"

In [9]:
model = xgb.XGBClassifier(learning_rate = 0.1, n_estimators=141, max_depth=5,
                            min_child_weight=3, gamma=0, subsample=0.8, colsample_bytree=0.8,objective= 'multi:softmax')
model.fit(X_train, Y_train)
Y_pred = model.predict(X_test)

In [10]:
print('Confusion Matrix\n',confusion_matrix(Y_test, Y_pred))
print('Cohen Kappa', cohen_kappa_score(Y_test, Y_pred, weights='quadratic'))
print('Accuracy Score', accuracy_score(Y_test, Y_pred))
print('MSE', mean_squared_error(Y_test, Y_pred))

Confusion Matrix
 [[  0  42  35   7  43]
 [  0 268 329  76 234]
 [  2 213 471 172 389]
 [  1 129 273 183 373]
 [  1  97 214  71 875]]
Cohen Kappa 0.3196618557002461
Accuracy Score 0.39951089373054693
MSE 1.9137394397510004


In [11]:
#print(model.feature_importances_)
sorted(range(len(model.feature_importances_)), key=lambda i: model.feature_importances_[i], reverse = True)[:20]

[163,
 1,
 329,
 324,
 310,
 315,
 126,
 0,
 286,
 331,
 334,
 37,
 220,
 313,
 235,
 145,
 268,
 108,
 143,
 270]